---
fabric_name: lg1
platform: qfx5120-48y-8c

ztp_server_ip: 192.168.251.201
ztp_group: ztp_group_10_2_205_6
ztp_mgmt_ip: 192.168.251.201
ztp_user: root
subnets:
  - subnet_205

host_interfaces:
  - name: xe-0/0/0
    description: Host Simulator
    vlan:
      - MANAGEMENT
      - STORAGE
      - VMOTION
      - NSX-TRANSPORT
      - NSX-TRANSPORT-EDGE
      - NSX-NS-2006
      - NSX-NS-2007
    tag: ue100
    mtu: 9030
    trunk: true
    speed: 10g
  - name: xe-0/0/1
    description: Host Simulator
    vlan:
      - MANAGEMENT
      - STORAGE
      - VMOTION
      - NSX-TRANSPORT
      - NSX-TRANSPORT-EDGE
      - NSX-NS-2006
      - NSX-NS-2007
    tag: ue101
    mtu: 9030
    trunk: true
    speed: 10g
  - name: xe-0/0/24
    description: Host Simulator
    vlan:
      - MANAGEMENT
      - STORAGE
      - VMOTION
      - NSX-TRANSPORT
      - NSX-TRANSPORT-EDGE
      - NSX-NS-2006
      - NSX-NS-2007
    tag: ue101
    mtu: 9030
    trunk: true
    speed: 10g

vlans:
  - name: MANAGEMENT
    id: 2001
    description: Management VLAN for NSX-T
  - name: VMOTION
    id: 2002
    description: vMotion VLAN for NSX-T
  - name: STORAGE
    id: 2003
    description: Storage VLAN for NSX-T
  - name: NSX-TRANSPORT
    id: 2004
    description: NSX-TRANSPORT VLAN for host to host communication
  - name: NSX-TRANSPORT-EDGE
    id: 2005
    description: ue900-t0edge-nsx-transport
  - name: NSX-NS-2006
    id: 2006
    description: Path from NSX-T to WAN on VLAN 2006
  - name: NSX-NS-2007
    id: 2007
    description: Path from NSX-T to WAN on VLAN 2007
