---
fabric_name: lg3
platform: qfx5120-48y-8c

ztp_server_ip: 172.18.162.69
ztp_group: ztp_group_172_18_162_69
ztp_mgmt_ip: 172.18.162.69
ztp_user: root
subnets:
  - subnet_4

host_interfaces:
  - name: ge-0/0/18
    description: test host ex2200-c
    vlan:
      - MANAGEMENT
      - STORAGE
      - VMOTION
      - NSX-TRANSPORT
      - NSX-TRANSPORT-EDGE
      - NSX-NS-2006
      - NSX-NS-2007
    tag: test-host
    mtu: 9030
    trunk: true
    speed: 10g
  - name: xe-0/0/0
    description: vsvh-211-ue100
    vlan:
      - MANAGEMENT
      - STORAGE
      - VMOTION
      - NSX-TRANSPORT
      - NSX-TRANSPORT-EDGE
      - NSX-NS-2006
      - NSX-NS-2007
    tag: ue100
    mtu: 9030
    trunk: true
    speed: 10g
  - name: xe-0/0/1
    description: vsvh-211-ue101
    vlan:
      - MANAGEMENT
      - STORAGE
      - VMOTION
      - NSX-TRANSPORT
      - NSX-TRANSPORT-EDGE
      - NSX-NS-2006
      - NSX-NS-2007
    tag: ue101
    mtu: 9030
    trunk: true
    speed: 10g
  - name: xe-0/0/2
    description: vsvh-211-ue102
    vlan:
      - MANAGEMENT
      - STORAGE
      - VMOTION
      - NSX-TRANSPORT
      - NSX-TRANSPORT-EDGE
      - NSX-NS-2006
      - NSX-NS-2007
    tag: ue102
    mtu: 9030
    trunk: true
    speed: 10g
  - name: xe-0/0/3
    description: vsvh-211-ue103
    vlan:
      - MANAGEMENT
      - STORAGE
      - VMOTION
      - NSX-TRANSPORT
      - NSX-TRANSPORT-EDGE
      - NSX-NS-2006
      - NSX-NS-2007
    tag: ue103
    mtu: 9030
    trunk: true
    speed: 10g
  - name: xe-0/0/4
    description: vsvh-211-ue104
    vlan:
      - MANAGEMENT
      - STORAGE
      - VMOTION
      - NSX-TRANSPORT
      - NSX-TRANSPORT-EDGE
      - NSX-NS-2006
      - NSX-NS-2007
    tag: ue104
    mtu: 9030
    trunk: true
    speed: 10g
vlans:
  - name: MANAGEMENT
    id: 2001
    description: Management VLAN for NSX-T
  - name: VMOTION
    id: 2002
    description: vMotion VLAN for NSX-T
  - name: STORAGE
    id: 2003
    description: Storage VLAN for NSX-T
  - name: NSX-TRANSPORT
    id: 2004
    description: NSX-TRANSPORT VLAN for host to host communication
  - name: NSX-TRANSPORT-EDGE
    id: 2005
    description: ue900-t0edge-nsx-transport
  - name: NSX-NS-2006
    id: 2006
    description: Path from NSX-T to WAN on VLAN 2006
  - name: NSX-NS-2007
    id: 2007
    description: Path from NSX-T to WAN on VLAN 2007
