fabric_name: spine
platform: qfx1002-72Q

ztp_server_ip: 172.18.162.68
ztp_group: ztp_group_172_18_162_68
ztp_mgmt_ip: 172.18.162.68
ztp_user: root
subnets: 
  - subnet_205

vlans:
  - name: MANAGEMENT
    id: 2001
    description: "Management VLAN for NSX-T"
    l3_interface: irb.2001
  - name: VMOTION
    id: 2002
    description: "vMotion VLAN for NSX-T"
    l3_interface: irb.2002
  - name: STORAGE
    id: 2003
    description: "Storage VLAN for NSX-T"
    l3_interface: irb.2003
  - name: NSX-TRANSPORT
    id: 2004
    description: "NSX-TRANSPORT VLAN for NSX-T in Leaf Group 3"
    l3_interface: irb.2004
  - name: NSX-TRANSPORT-EDGE
    id: 2005
    description: "ue900-t0edge-nsx-transport"
    l3_interface: irb.2005

