---
image: jinstall-host-qfx-5e-x86-64-18.4-20190424.0-secure-signed.tgz
ztp_server_ip: 192.168.105.5
host_interfaces:
  - name: ae5
    description: testdev3
    esi: true
    vlan:
      - 100
      - 200
      - 300
    tag: testdev3
    mtu: 9216
    lacp:
      active: true
    trunk: true
  - name: ae6
    description: testdev4
    esi: true
    vlan:
      - 100
      - 200
      - 300
    tag: testdev4
    mtu: 9216
    lacp:
      active: true
    trunk: true
  - name: xe-2/0/1
    description: testdev3
    tag: testdev3
    ae: 5
  - name: xe-2/0/2
    description: testdev3
    tag: testdev3
    ae: 5
  - name: xe-2/0/3
    description: testdev4
    tag: testdev4
    ae: 6
  - name: xe-2/0/4
    description: testdev4
    tag: testdev4
    ae: 6
vlans:
  - name: vlan.5
    id: 5
  - name: vlan.12
    id: 12
  - name: vlan.30
    id: 30
  - name: vlan.60
    id: 60
  - name: vlan.70
    id: 70
  - name: vlan.77
    id: 77
  - name: vlan.80
    id: 80
