---
fabric_name: vc1
ztp_server_ip: 10.2.205.6
ztp_group: ztp_group_10_2_205_6
ztp_mgmt_ip: 192.168.254.220
ztp_user: root
subnets:
  - subnet_205
host_interfaces:
  - name: ae0
    description: Trunk to ESX127
    esi: true
    vlan:
      - finance
      - hr
      - marketing
    tag: ESX127
    mtu: 9216
    lacp:
      active: true
    trunk: true
  - name: ae1
    description: Trunk to ESX127
    esi: true
    vlan:
      - finance
      - hr
      - marketing
    tag: ESX113
    mtu: 9216
    lacp:
      active: true
    trunk: true
  - name: et-0/0/48
    description: ae0 member
    tag: ESX127
    ae: 0
  - name: xe-0/0/0
    description: ae1 member
    tag: ESX113
    ae: 1
vlans:
  - name: finance
    id: 100
  - name: hr
    id: 200
  - name: marketing
    id: 999
