---
all:
  children:
    ea-lab:
      children:
        leaf:
          children:
            lg1:
              hosts:
                U2410NJ-ULAB: 
                  ansible_host: 172.17.4.10
                  serial_number: XH3119370107
                U2411NJ-ULAB:
                  ansible_host: 172.17.4.11
                  serial_number: XH3119370077
            lg2:
              hosts:
                U2412NJ-ULAB:
                  ansible_host: 172.17.4.12
                  serial_number: XH3119370120
                U2413NJ-ULAB:
                  ansible_host: 172.17.4.13
                  serial_number: XH3119370015
            lg3:
              hosts:
                U2414NJ-ULAB:
                  ansible_host: 172.17.4.14
                  serial_number: XH3119370048
                U2415NJ-ULAB:
                  ansible_host: 172.17.4.15
                  serial_number: XH3119370134
        spine:
          hosts:
            U2402IJ-ULAB:
              ansible_host: 172.17.4.2
              serial_number: EG885
            U2403IJ-ULAB:
              ansible_host: 172.17.4.3
              serial_number: EJ340
        distro_router:
          hosts:
            U2400DJ-ULAB:
              ansible_host: 172.17.4.100
              serial_number: V6857
            U2401DJ-ULAB:
              ansible_host: 172.17.4.101
              serial_number: V6730

    ztp_group_172_18_162_68:
      children:
        subnet_205:
          hosts:
            U2402IJ-ULAB:
            U2403IJ-ULAB:
            U2410NJ-ULAB:
            U2411NJ-ULAB:
            U2412NJ-ULAB:
            U2413NJ-ULAB:
            U2414NJ-ULAB:
            U2415NJ-ULAB:
