---
serial: V2945
image: fake.image

lo0_ip_cidr: 10.255.255.100/32

wan_interfaces:
  - description: to WAN
    name: et-0/0/2
    ip_cidr: 10.55.55.2/30
    wan:
      neighbor_ip: 10.55.55.1
      remote_as: 65200
    speed: 40g
    mtu: 9216

dc_interfaces:
  - description: U4002-TCH
    name: et-0/0/0
    ip_cidr: 10.1.1.0/31
    underlay:
      neighbor_ip: 10.1.1.1
    overlay:
      neighbor_ip: 10.255.255.102
    speed: 40g
    mtu: 9216
  - description: U4003-TCH
    name: et-0/0/1
    ip_cidr: 10.1.1.2/31
    underlay:
      neighbor_ip: 10.1.1.3
    overlay:
      neighbor_ip: 10.255.255.103
    speed: 40g
    mtu: 9216



mgmt_interface:
  - description: Management
    name: fxp0
    ip_cidr: '{{ mgmt_ip_cidr }}'
loopback_interfaces:
  - description: Loopback
    name: lo0
    ip_cidr: '{{ lo0_ip_cidr }}'
snmp_encrypted:
  - user: LABsnmpv3
    auth_key: $9$C-zqA1RleW-dsXxk.P56/vW87bsJZjkqfNds4aZkq1REhKMVwYGjHJZ69Au1Is2gaDifTz39Aq.IESrvM7-VYaZGDim5QxNqmP5F3/Ctu0IyrvWxNvMjH
    priv_key: $9$B8n1ylLX-2gJbwTz36u07-dsoJHkPTQnYgJDikTQyleKxN4aZqP5HkuO1EyrJGUimfn/CtO1QzreM87Ns24ZikqmfF69wY
  - user: test
    auth_key: $9$b3w4aqmfQz6YgfT3npuX7N-VY4aZH.P4on/9A0OVws4Ujq.5zn/goDkmfn6evMLX-bwg4ZUSraZDif5ylevX7s24Djqoa/CApRE24oJjHz36/tuGDHm
    priv_key: $9$veFMxN4aZDjq8XZUHkTQcyrlK8xNd2oJx7k.mfzFKMWxbs4oGjk.X7wgaZkqO1IhclvMXxdbtuNdwYZGp0O1cyWLxws47N
