serial: DC064
image: jinstall-host-qfx-10-f-x86-64-19.4R1.10-secure-signed.tgz

lo0_ip_cidr: 10.255.255.102/32
lo0_1_ip_cidr: 10.255.255.102/32

dc_interfaces:
  - description: U4000DJ-TCH
    name: et-0/0/6
    ip_cidr: 10.1.1.1/31
    underlay:
      neighbor_ip: 10.1.1.0
    overlay:
      neighbor_ip: 10.255.255.100
  - description: U4001DJ-TCH
    name: et-0/0/7
    ip_cidr: 10.1.1.5/31
    underlay:
      neighbor_ip: 10.1.1.4
    overlay:
      neighbor_ip: 10.255.255.101

fabric_interfaces:
  - description: U4010NJ-TCH
    name: et-0/0/0
    ip_cidr: 10.1.1.8/31
    underlay:
      neighbor_ip: 10.1.1.9
    overlay:
      neighbor_ip: 10.255.255.110
  - description: U4011NJ-TCH
    name: et-0/0/1
    ip_cidr: 10.1.1.10/31
    underlay:
      neighbor_ip: 10.1.1.11 
    overlay:
      neighbor_ip: 10.255.255.111

mgmt_interface:
  - description: Management
    name: em0
    ip_cidr: "{{ mgmt_ip_cidr }}"

loopback_interfaces:
  - description: Loopback
    name: lo0
    units:
      - number: 0
        ip_cidr: "{{ lo0_ip_cidr }}"
      - number: 1
        ip_cidr: "{{ lo0_1_ip_cidr }}"

overlay_interfaces:
  - description: IRB
    name: irb
    units:
      - number: 2001
        description: "VCF Management"
        ip_cidr: 172.31.170.2/24
        vni_gw: 172.31.170.1
        network: 172.31.170.0/24
        dhcp_helper: true
      - number: 2002
        description: "vMotion"
        ip_cidr: 172.31.169.130/25
        vni_gw: 172.31.169.129
        network: 172.31.169.128/25
        dhcp_helper: true
      - number: 2003
        description: "vSAN"
        ip_cidr: 172.31.171.2/25
        vni_gw: 172.31.171.1
        network: 172.31.171.0/25
        dhcp_helper: true
      - number: 2004
        description: "NSX Transport"
        ip_cidr: 172.31.171.130/25
        vni_gw: 172.31.171.129
        network: 172.31.171.128/25
        vrrp_group: 30
        dhcp_helper: true
      - number: 2005
        description: "ue900-t0edge-nsx-transport"
        ip_cidr: 172.31.172.2/25
        vni_gw: 172.31.172.1
        network: 172.31.172.0/25
        vrrp_group: 30
        dhcp_helper: false