serial: V2565
image: fake.image

lo0_ip_cidr: 10.255.255.101/32

wan_interfaces:
  - description: "to WAN - fake"
    name: et-0/0/2
    ip_cidr: 10.10.10.1/30
    wan:
      neighbor_ip: 10.10.10.2
      remote_as: 65200
    speed: 40g
    mtu: 9216

dc_interfaces:
  - description: U4002-TCH
    name: et-0/0/0
    ip_cidr: 10.1.1.4/31
    underlay:
      neighbor_ip: 10.1.1.5
    overlay:
      neighbor_ip: 10.255.255.102
    speed: 40g
    mtu: 9216
  - description: U4003-TCH
    name: et-0/0/1
    ip_cidr: 10.1.1.6/31
    underlay:
      neighbor_ip: 10.1.1.7
    overlay:
      neighbor_ip: 10.255.255.103
    speed: 40g
    mtu: 9216


mgmt_interface:
  - description: Management
    name: fxp0
    ip_cidr: "{{ mgmt_ip_cidr }}"

loopback_interfaces:
  - description: Loopback
    name: lo0
    ip_cidr: "{{ lo0_ip_cidr }}"