serial: DP449
image: jinstall-host-qfx-10-f-x86-64-19.4R1.10-secure-signed.tgz

lo0_ip_cidr: 10.255.255.103/32
lo0_1_ip_cidr: "{{ lo0_ip_cidr }}"

dc_interfaces:
  - description: U4000DJ-TCH
    name: et-0/0/6
    ip_cidr: 10.1.1.3/31
    underlay:
      neighbor_ip: 10.1.1.2
    overlay:
      neighbor_ip: 10.255.255.100
    speed: 40g
  - description: U4001DJ-TCH
    name: et-0/0/7
    ip_cidr: 10.1.1.7/31
    underlay:
      neighbor_ip: 10.1.1.6
    overlay:
      neighbor_ip: 10.255.255.101
    speed: 40g

fabric_interfaces:
  - description: U4010NJ-TCH
    name: et-0/0/0
    ip_cidr: 10.1.1.12/31
    underlay:
      neighbor_ip: 10.1.1.13
    overlay:
      neighbor_ip: 10.255.255.110
    speed: 40g
  - description: U4011NJ-TCH
    name: et-0/0/1
    ip_cidr: 10.1.1.14/31
    underlay:
      neighbor_ip: 10.1.1.15 
    overlay:
      neighbor_ip: 10.255.255.111
    speed: 40g

mgmt_interface:
  - description: Management
    name: em0
    ip_cidr: "{{ mgmt_ip_cidr }}"

loopback_interfaces:
  - description: Loopback
    name: lo0.0
    ip_cidr: "{{ lo0_ip_cidr }}"
  - description: Loopback for OVERLAY_VR
    name: lo0.1
    ip_cidr: "{{ lo0_1_ip_cidr }}"

overlay_interfaces:
  - name: irb.2001
    description: "VCF Management"
    ip_cidr: 172.31.170.3/24
    vni_gw: 172.31.170.1
    network: 172.31.170.0/24
    dhcp_helper: true
  - name: irb.2002
    description: "vMotion"
    ip_cidr: 172.31.169.131/25
    vni_gw: 172.31.169.129
    network: 172.31.169.128/25
    dhcp_helper: true
  - name: irb.2003
    description: "vSAN"
    ip_cidr: 172.31.171.3/25
    vni_gw: 172.31.171.1
    network: 172.31.171.0/25
    dhcp_helper: true
  - name: irb.2004
    description: "NSX Transport"
    ip_cidr: 172.31.171.131/25
    vni_gw: 172.31.171.129
    network: 172.31.171.128/25
    dhcp_helper: true
  - name: irb.2005
    description: "ue900-t0edge-nsx-transport"
    ip_cidr: 172.31.172.3/25
    vni_gw: 172.31.172.1
    network: 172.31.172.0/25
    dhcp_helper: false

nsx_interface:
  - name: irb.2006
    description: "NSX Edge"
    ip_cidr: 172.17.2.57/29
    neighbor:
      - 172.17.2.58
      - 172.17.2.59

nsx_vlan:
  name: NSX-NS-2006
  id: 2006
  description: "Path from NSX-T to WAN on VLAN 2006"
  l3_interface: irb.2006